apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  labels:
    app: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: backstageacr.azurecr.io/portal:v1
          ports:
            - containerPort: 8045
---
apiVersion: v1
kind: Service
metadata:
  name: portalsvc
  labels:
    app: portal
spec:
  type: LoadBalancer
  selector:
    app: portal
  ports:
    - port: 80
      targetPort: 8045
