apiVersion : apps/v1
kind: Deployment
metadata:
  name: portal 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal 
    spec:
      containers:
        - name: portal 
          image: backstageacr.azurecr.io/portal
          ports:
          - containerPort: 8045
