apiVersion: v1
kind: Service # Set up the service kind
metadata:
  name: portal-service
  labels:
    app: portal
spec:
  type: LoadBalancer # Here we use load balancer service.
  selector:
    app: portal
  ports:
    - port: 80
      targetPort: 8045
